name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Test multiline step
        run: |
            echo "First line"
            echo "Second line"
      - name: Print good bye
        run: echo "Good bye"
